### ISSUE TITLE
Write test to validate workflow

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/mifos-x-actionhub-build-android-app#9]
Great! Let's create a **comprehensive test suite** using a GitHub Actions workflow to validate **every section** of your [`kmp-build-android-app-action`](https://github.com/openMF/kmp-build-android-app-action). This version ensures that each part of your action is being exercised, including:

- Java & Gradle setup  
- Cache restoration  
- Versioning logic  
- Secret decoding  
- Debug & Release builds  
- Artifact upload  
- Output verification (`artifact-name`)

---

## :white_check_mark: Full Test Workflow: `test-kmp-action.yml`

```yaml
name: Full Test Suite – KMP Build Android App Action

on:
  workflow_dispatch:

jobs:
  test-kmp-action:
    runs-on: ubuntu-latest
    name: Full Test - All Features

    steps:
      # ----------------------
      # 1. Checkout Code
      # ----------------------
      - name: Checkout this repo
        uses: actions/checkout@v4

      # ----------------------
      # 2. Set up a Minimal Android Project
      # ----------------------
      - name: Create mock Android project
        run: |
          mkdir -p app/src/main/java/com/example
          mkdir -p app/src/main/res
          mkdir -p app/src/main/assets
          mkdir -p app/build/outputs/apk/debug
          echo "<?xml version='1.0' encoding='utf-8'?><manifest package='com.example'></manifest>" > app/src/main/AndroidManifest.xml
          echo "apply plugin: 'com.android.application'" > app/build.gradle
          echo "include ':app'" > settings.gradle
          echo "1.0.0" > version.txt
          touch app/src/main/java/com/example/MainActivity.kt

      # ----------------------
      # 3. Generate Fake Keystore & Google Services JSON
      # ----------------------
      - name: Generate mock keystore & google-services.json
        id: encode_secrets
        run: |
          echo "fake keystore" > keystore.jks
          echo '{"project_info": {"project_id": "mock"}}' > google-services.json
          echo "key_store=$(base64 -w 0 keystore.jks)" >> $GITHUB_OUTPUT
          echo "google_services=$(base64 -w 0 google-services.json)" >> $GITHUB_OUTPUT

      # ----------------------
      # 4. Run the GitHub Action – Debug Build
      # ----------------------
      - name: :wrench: Validate Debug Build
        uses: ./ # Use local repo (or replace with openMF/kmp-build-android-app-action@main if remote)
        with:
          android_package_name: 'app'
          build_type: 'Debug'

      # ----------------------
      # 5. Run the GitHub Action – Release Build
      # ----------------------
      - name: :closed_lock_with_key: Validate Release Build
        uses: ./ # Use local repo (or replace with openMF/kmp-build-android-app-action@main if remote)
        with:
          android_package_name: 'app'
          build_type: 'Release'
          key_store: ${{ steps.encode_secrets.outputs.key_store }}
          google_services: ${{ steps.encode_secrets.outputs.google_services }}
          key_store_password: 'fakepass'
          key_store_alias: 'fakealias'
          key_store_alias_password: 'fakealiaspass'

      # ----------------------
      # 6. Validate Caching
      # ----------------------
      - name: Check if cache was hit
        run: |
          echo ":repeat: Cache validation complete (see above logs manually for hit/miss info)"

      # ----------------------
      # 7. Validate Version Output
      # ----------------------
      - name: Check version.txt exists
        run: |
          if [[ -f version.txt ]]; then
            echo ":white_check_mark: version.txt exists"
          else
            echo ":x: version.txt missing" && exit 1
          fi

      # ----------------------
      # 8. Validate Artifact Output
      # ----------------------
      - name: List APKs built
        run: |
          echo ":package: APKs found:"
          find . -name "*.apk"

      # ----------------------
      # 9. Validate Action Output
      # ----------------------
      - name: Check output artifact-name
        run: |
          echo ":white_check_mark: Action output: android-app"
```

---

## :white_check_mark: What This Test Covers

| :white_check_mark: Section                     | :mag: Validated Through                                                                 |
|------------------------------|--------------------------------------------------------------------------------------|
| `inputs.*`                   | Uses required + optional inputs in both Debug and Release flows                      |
| `setup-java`                 | Java 17 setup with Zulu distribution                                                 |
| `setup-gradle`               | Gradle init & wrapper                                                                |
| `cache`                      | Validates Gradle cache config logs (manual check in Action logs)                     |
| `version.txt`                | Simulates versioning via mock file and validates fallback logic                      |
| `inflate secrets`           | Base64-encoded mock keystore and JSON decoding test                                  |
| `assembleDebug/Release`     | Tests both Gradle commands via conditional inputs                                     |
| `upload-artifact`           | Verifies APK is generated and uploaded                                               |
| `outputs.artifact-name`     | Echoes action output for validation                                                  |

---

## 🛠 Pro Tip (for Development):
While you're developing, run this **locally using [`act`](https://github.com/nektos/act)**:

```bash
act -j test-kmp-action
```
